version: '3.5'

services:
  kong-migrations:
    image: kong:1.0-centos
    depends_on:
      - db
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
      KONG_PG_HOST: db
      KONG_PG_PASSWORD: kong
      KONG_PG_USER: kong
    networks:
      - kong-network
    links:
      - db:db
    command: bash -c 'kong migrations bootstrap && kong migrations reset -y && kong migrations bootstrap && kong migrations up'
    restart: on-failure
  kong:
    image: kong
    depends_on:
      - db
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_CASSANDRA_CONTACT_POINTS: db
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
      KONG_PG_HOST: db
      KONG_PG_PASSWORD: kong
      KONG_PG_USER: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
    networks:
      - kong-network
    links:
      - db:db
    ports:
      - '8000:8000/tcp'
      - '8001:8001/tcp'
      - '8443:8443/tcp'
      - '8444:8444/tcp'
    restart: on-failure
  db:
    image: postgres:9.5
    environment:
      POSTGRES_DB: ${KONG_PG_DATABASE:-kong}
      POSTGRES_PASSWORD: kong
      POSTGRES_USER: kong
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', '${KONG_PG_USER:-kong}']
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    networks:
      - kong-network
    stdin_open: true
    tty: true

networks:
  kong-network:
    name: kong-network
    driver: bridge
